version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install
  pre_build:
    commands:
      - export AWS_DEFAULT_REGION=us-east-1
  build:
    commands:
      - npm test
      - sam build