version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install
  pre_build:
    commands:
      - cd Services && cd create_service && npm test
      - cd ../..
  build:
    commands:
      - sam build
  post_build:
    commands:
      - sam deploy
