version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - export AWS_DEFAULT_REGION=us-east-1
      - cd Services && cd create_service && npm install && npm test
      - cd ../..
  build:
    commands:
      - sam build
  post_build:
    commands:
      - sam deploy
