version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - npm install
      - export AWS_DEFAULT_REGION=us-east-1
  build:
    commands:
      - npm test
  post_build:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket data-palmtech --output-template-file packaged-template.yaml 
artifacts:
  files:
    - packaged-template.yaml 