version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install
  pre_build:
    commands:
      - export AWS_DEFAULT_REGION=us-east-1
  build:
    commands:
      - npm test
  post_build:
    commands:
      - aws cloudformation package --template-file template.yaml --stack-name my-stack-name --s3-bucket api-palmtech-devops --capabilities CAPABILITY_IAM